### ISSUE TITLE
Hasn't worked since 0.105.0b4

### ISSUE THREAD

**Issue by brianhanifin** [custom-components/readme#1]
## Version of the custom_component

0.1.1

## Configuration

I tried replacing my entire /templates/README.j2 with the following line and got the same error.

```yaml

# Test

```

## Describe the bug
This was working great within the last week or so. I can tell you that I was running Home Assistant 0.105.0b4 the last time this worked (see the version stamped at the top of my [README.md](https://github.com/brianhanifin/Home-Assistant-Config/blob/master/README.md).)

Executing `readme.generate` from the Developer Tools > Services page gives a `Failed to call service readme/generate. 'documentation'` error.

Let me know if I can provide more info.

## Debug log

```text

2020-02-07 20:41:41 INFO (MainThread) [homeassistant.helpers.script] Script ci_prep: Executing step call service
2020-02-07 20:41:41 ERROR (MainThread) [homeassistant.components.script] Error executing script script.ci_prep. Unknown error for call_service at pos 2:
  Traceback (most recent call last):   File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 272, in async_turn_on     await self.script.async_run(kwargs.get(ATTR_VARIABLES), context)
   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 247, in async_run
     await self._handle_action(action, variables, context)
   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 331, in _handle_action
     await self._actions[_determine_action(action)](action, variables, context)
   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 413, in _async_call_service
     context=context,
   File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 96, in async_call_from_config
     domain, service_name, service_data, blocking=blocking, context=context
   File "/usr/src/homeassistant/homeassistant/core.py", line 1226, in async_call
     await asyncio.shield(self._execute_service(handler, service_call))
   File "/usr/src/homeassistant/homeassistant/core.py", line 1251, in _execute_service
     await handler.func(service_call)
   File "/config/custom_components/readme/__init__.py", line 167, in service_generate
     custom_components = get_custom_components(hass)
   File "/config/custom_components/readme/__init__.py", line 200, in get_custom_components
     "documentation": content["documentation"], KeyError: 'documentation'

```

**Comment by ludeeus** [comment]
You have a custom component without the documentation key

**Comment by brianhanifin** [comment]
That was it. I have narrowed it down to `uilogs`. I have [filed a bug report in that repo](https://github.com/custom-components/uilogs/issues/2).
