### ISSUE TITLE
KeyError: 'name'

### ISSUE THREAD

**Issue by aneisch** [custom-components/readme#6]
## Version of the custom_component

VERSION = "0.2.1"

## Configuration

```yaml
readme:
```

## Describe the bug
Key error with hacs.repositories file.

## Debug log

```text
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 130, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1260, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1295, in _execute_service
    await handler.func(service_call)
  File "/config/custom_components/readme/__init__.py", line 168, in service_generate
    hacs_components = get_hacs_components(hass)
  File "/config/custom_components/readme/__init__.py", line 208, in get_hacs_components
    "name": get_repository_name(repository),
  File "/config/custom_components/readme/__init__.py", line 221, in get_repository_name
    name = repository["repository_manifest"]["name"]
KeyError: 'name'
```

**Comment by aneisch** [comment]
Seeing this error again in Home Assistant v0.114.0 and integration v0.2.1.

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 191, in _async_step
    await getattr(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 380, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1308, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1343, in _execute_service
    await handler.func(service_call)
  File "/config/custom_components/readme/__init__.py", line 168, in service_generate
    hacs_components = get_hacs_components(hass)
  File "/config/custom_components/readme/__init__.py", line 208, in get_hacs_components
    "name": get_repository_name(repository),
  File "/config/custom_components/readme/__init__.py", line 221, in get_repository_name
    name = repository["repository_manifest"]["name"]
KeyError: 'name'
```

**Comment by edenhaus** [comment]
> Seeing this error again in Home Assistant v0.114.0 and integration v0.2.1.
> 
> ```
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 191, in _async_step
>     await getattr(
>   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 380, in _async_call_service_step
>     await service_task
>   File "/usr/src/homeassistant/homeassistant/core.py", line 1308, in async_call
>     task.result()
>   File "/usr/src/homeassistant/homeassistant/core.py", line 1343, in _execute_service
>     await handler.func(service_call)
>   File "/config/custom_components/readme/__init__.py", line 168, in service_generate
>     hacs_components = get_hacs_components(hass)
>   File "/config/custom_components/readme/__init__.py", line 208, in get_hacs_components
>     "name": get_repository_name(repository),
>   File "/config/custom_components/readme/__init__.py", line 221, in get_repository_name
>     name = repository["repository_manifest"]["name"]
> KeyError: 'name'
> ```

Until @ludeeus is releasing a new version, you can select in hacs the version **master**, where the fix is already included.
