### ISSUE TITLE
Failed to generate 'name' error

### ISSUE THREAD

**Issue by yieldhog** [custom-components/readme#9]
Failed to generate 'name' error. Default config, seems to generate ui-lovelace.yaml but breaks otherwise.

## Version of the custom_component
0.2.1 (installed via HACS)

Home Assistant 0.113.2

## Configuration

```
readme:
  - convert_lovelace: true
```

Using the default README.j2

## Debug log

```
'name'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 125, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1281, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1316, in _execute_service
    await handler.func(service_call)
  File "/config/custom_components/readme/__init__.py", line 168, in service_generate
    hacs_components = get_hacs_components(hass)
  File "/config/custom_components/readme/__init__.py", line 208, in get_hacs_components
    "name": get_repository_name(repository),
  File "/config/custom_components/readme/__init__.py", line 221, in get_repository_name
    name = repository["repository_manifest"]["name"]
KeyError: 'name'

```

**Comment by cjd** [comment]
See https://github.com/custom-components/readme/issues/6

**Comment by yieldhog** [comment]
@cjd got it, I see. Sorry didn't previously see the closed issue. In looking at it, is it resolved or is there a workaround? Wasn't clear to me as I am on the latest versions of HACS and generate readme and still getting errors/won't run. Thanks

**Comment by cjd** [comment]
It is fixed in github source, but the fix hasn't been released to HACS as yet (that I can see)
For now you could grab the modified file from https://raw.githubusercontent.com/custom-components/readme/master/custom_components/readme/__init__.py and put it in the custom_components/readme directory, overwritting the existing version
That worked for me so far

**Comment by yieldhog** [comment]
@cjd that worked -- in case anyone else is having an issue. Thanks!
